name: CI
jobs:
  test-node:
    runs-on: ubuntu-latest
  release:
    needs:
      - test-node
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4.1.3
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: 20.15.0
          cache: npm
          cache-dependency-path: package-lock.json
      - name: release
        run: npx semantic-release
        env:
          CI: "true"
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
